addons:
- include:
    stemcell:
    - os: ubuntu-trusty
    - os: ubuntu-xenial
  jobs:
  - name: bosh-dns
    properties:
      api:
        client:
          tls:
            ca: ((dns_api_client_tls))
            certificate: ((dns_api_client_tls_certificate))
            private_key: ((dns_api_client_tls_private_key))
        server:
          tls:
            ca: ((dns_api_server_tls))
            certificate: ((dns_api_server_tls_certificate))
            private_key: ((dns_api_server_tls_private_key))
      cache:
        enabled: true
      health:
        client:
          tls:
            ca: ((dns_healthcheck_client_tls))
            certificate: ((dns_healthcheck_client_tls_certificate))
            private_key: ((dns_healthcheck_client_tls_private_key))
        enabled: true
        server:
          tls:
            ca: ((dns_healthcheck_server_tls))
            certificate: ((dns_healthcheck_server_tls_certificate))
            private_key: ((dns_healthcheck_server_tls_private_key))
    release: bosh-dns
  name: bosh-dns
- jobs:
  - name: kubo-dns-aliases
    release: kubo
  name: bosh-dns-aliases
features:
  use_dns_addresses: true
instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: apply-specs
    properties:
      addons:
      - kube-dns
      - metrics-server
      - heapster
      - kubernetes-dashboard
      admin-password: ((kubo-admin-password))
      admin-username: admin
      api-token: ((kubelet-password))
      tls:
        heapster:
          ca: ((tls-heapster))
          certificate: ((tls-heapster-certificate))
          private_key: ((tls-heapster-private_key))
        influxdb:
          ca: ((tls-influxdb))
          certificate: ((tls-influxdb-certificate))
          private_key: ((tls-influxdb-private_key))
        kubernetes:
          ca: ((tls-kubernetes))
          certificate: ((tls-kubernetes-certificate))
          private_key: ((tls-kubernetes-private_key))
        kubernetes-dashboard:
          ca: ((tls-kubernetes-dashboard))
          certificate: ((tls-kubernetes-dashboard-certificate))
          private_key: ((tls-kubernetes-dashboard-private_key))
        metrics-server: ((tls-metrics-server))
    release: kubo
  lifecycle: errand
  name: apply-addons
  networks:
  - name: default
  stemcell: default
  vm_type: minimal
- azs:
  - z1
  - z2
  - z3
  instances: 1
  jobs:
  - name: bpm
    release: bpm
  - name: flanneld
    release: kubo
  - name: kube-apiserver
    properties:
      admin-password: ((kubo-admin-password))
      admin-username: admin
      k8s-args:
        audit-log-maxage: 0
        audit-log-maxbackup: 0
        audit-log-maxsize: 0
        audit-log-path: /var/vcap/sys/log/kube-apiserver/audit.log
        audit-policy-file: /var/vcap/jobs/kube-apiserver/config/audit_policy.yml
        authorization-mode: RBAC
        client-ca-file: /var/vcap/jobs/kube-apiserver/config/kubernetes.pem
        disable-admission-plugins: []
        enable-admission-plugins: []
        enable-aggregator-routing: true
        enable-bootstrap-token-auth: true
        enable-swagger-ui: true
        etcd-cafile: /var/vcap/jobs/kube-apiserver/config/etcd-ca.crt
        etcd-certfile: /var/vcap/jobs/kube-apiserver/config/etcd-client.crt
        etcd-keyfile: /var/vcap/jobs/kube-apiserver/config/etcd-client.key
        kubelet-client-certificate: /var/vcap/jobs/kube-apiserver/config/kubelet-client-cert.pem
        kubelet-client-key: /var/vcap/jobs/kube-apiserver/config/kubelet-client-key.pem
        proxy-client-cert-file: /var/vcap/jobs/kube-apiserver/config/kubernetes.pem
        proxy-client-key-file: /var/vcap/jobs/kube-apiserver/config/kubernetes-key.pem
        requestheader-allowed-names: aggregator
        requestheader-client-ca-file: /var/vcap/jobs/kube-apiserver/config/kubernetes.pem
        requestheader-extra-headers-prefix: X-Remote-Extra-
        requestheader-group-headers: X-Remote-Group
        requestheader-username-headers: X-Remote-User
        runtime-config: api/v1
        secure-port: 8443
        service-account-key-file: /var/vcap/jobs/kube-apiserver/config/service-account-public-key.pem
        service-cluster-ip-range: 10.100.200.0/24
        storage-media-type: application/json
        tls-cert-file: /var/vcap/jobs/kube-apiserver/config/kubernetes.pem
        tls-private-key-file: /var/vcap/jobs/kube-apiserver/config/kubernetes-key.pem
        token-auth-file: /var/vcap/jobs/kube-apiserver/config/tokens.csv
        v: 2
      kube-controller-manager-password: ((kube-controller-manager-password))
      kube-proxy-password: ((kube-proxy-password))
      kube-scheduler-password: ((kube-scheduler-password))
      kubelet-drain-password: ((kubelet-drain-password))
      kubelet-password: ((kubelet-password))
      service-account-public-key: ((service-account-key-public_key))
      tls:
        kubelet-client:
          ca: ((tls-kubelet-client))
          certificate: ((tls-kubelet-client-certificate))
          private_key: ((tls-kubelet-client-private_key))
        kubernetes:
          ca: ((tls-kubernetes))
          certificate: ((tls-kubernetes-certificate))
          private_key: ((tls-kubernetes-private_key))
    release: kubo
  - name: kube-controller-manager
    properties:
      api-token: ((kube-controller-manager-password))
      cluster-signing:
          ca: ((kubo_ca))
          certificate: ((kubo_ca_certificate))
          private_key: ((kubo_ca_private_key))
      k8s-args:
        cluster-name: kubernetes
        cluster-signing-cert-file: /var/vcap/jobs/kube-controller-manager/config/cluster-signing-ca.pem
        cluster-signing-key-file: /var/vcap/jobs/kube-controller-manager/config/cluster-signing-key.pem
        kubeconfig: /var/vcap/jobs/kube-controller-manager/config/kubeconfig
        leader-elect: true
        root-ca-file: /var/vcap/jobs/kube-controller-manager/config/ca.pem
        service-account-private-key-file: /var/vcap/jobs/kube-controller-manager/config/service-account-private-key.pem
        terminated-pod-gc-threshold: 100
        use-service-account-credentials: true
        v: 2
      service-account-private-key: ((service-account-key-private_key))
      tls:
        kubernetes:
          ca: ((tls-kubernetes))
          certificate: ((tls-kubernetes-certificate))
          private_key: ((tls-kubernetes-private_key))
    release: kubo
  - name: kube-scheduler
    properties:
      api-token: ((kube-scheduler-password))
      kube-scheduler-configuration:
        apiVersion: componentconfig/v1alpha1
        clientConnection:
          kubeconfig: /var/vcap/jobs/kube-scheduler/config/kubeconfig
        disablePreemption: false
        kind: KubeSchedulerConfiguration
      tls:
        kubernetes:
          ca: ((tls-kubernetes))
          certificate: ((tls-kubernetes-certificate))
          private_key: ((tls-kubernetes-private_key))
    release: kubo
  - name: kubernetes-roles
    properties:
      admin-password: ((kubo-admin-password))
      admin-username: admin
      tls:
        kubernetes:
          ca: ((tls-kubernetes))
          certificate: ((tls-kubernetes-certificate))
          private_key: ((tls-kubernetes-private_key))
    release: kubo
  - name: etcd
    properties:
      etcd:
        dns_suffix: etcd.cfcr.internal
      tls:
        etcd:
          ca: ((tls-etcd-v0-17-0-ca))
          certificate: ((tls-etcd-v0-17-0-certificate))
          private_key: ((tls-etcd-v0-17-0-private_key))
        etcdctl:
          ca: ((tls-etcdctl-ca))
          certificate: ((tls-etcdctl-certificate))
          private_key: ((tls-etcdctl-private_key))
        peer:
          ca: ((tls-etcd-v0-17-0-ca))
          certificate: ((tls-etcd-v0-17-0-certificate))
          private_key: ((tls-etcd-v0-17-0-private_key))
    release: cfcr-etcd
  - name: smoke-tests
    release: kubo
  name: master
  networks:
  - name: default
  persistent_disk: 5120
  stemcell: default
  vm_type: small
- azs:
  - z1
  - z2
  - z3
  instances: 3
  jobs:
  - name: flanneld
    release: kubo
  - name: docker
    properties:
      bridge: cni0
      default_ulimits:
      - nofile=65536
      env: {}
      flannel: true
      ip_masq: false
      iptables: false
      log_level: error
      log_options:
      - max-size=128m
      - max-file=2
      storage_driver: overlay2
      store_dir: /var/vcap/data
    release: docker
  - name: kubernetes-dependencies
    release: kubo
  - name: kubelet
    properties:
      api-token: ((kubelet-password))
      drain-api-token: ((kubelet-drain-password))
      k8s-args:
        allow-privileged: false
        cni-bin-dir: /var/vcap/jobs/kubelet/packages/cni/bin
        container-runtime: docker
        docker: unix:///var/vcap/sys/run/docker/docker.sock
        docker-endpoint: unix:///var/vcap/sys/run/docker/docker.sock
        keep-terminated-pod-volumes: false
        kubeconfig: /var/vcap/jobs/kubelet/config/kubeconfig
        network-plugin: cni
      kubelet-configuration:
        apiVersion: kubelet.config.k8s.io/v1beta1
        authentication:
          anonymous:
            enabled: false
          x509:
            clientCAFile: /var/vcap/jobs/kubelet/config/kubelet-client-ca.pem
        authorization:
          mode: Webhook
        clusterDNS:
        - 10.100.200.10
        clusterDomain: cluster.local
        failSwapOn: false
        kind: KubeletConfiguration
        readOnlyPort: 0
        serializeImagePulls: false
        tlsCertFile: /var/vcap/jobs/kubelet/config/kubelet.pem
        tlsPrivateKeyFile: /var/vcap/jobs/kubelet/config/kubelet-key.pem
      tls:
        kubelet:
          ca: ((tls-kubelet))
          certificate: ((tls-kubelet-certificate))
          private_key: ((tls-kubelet-private_key))
        kubelet-client-ca:
          certificate: ((tls-kubelet-client))
        kubernetes:
          ca: ((tls-kubernetes))
          certificate: ((tls-kubernetes-certificate))
          private_key: ((tls-kubernetes-private_key))
    release: kubo
  - name: kube-proxy
    properties:
      api-token: ((kube-proxy-password))
      kube-proxy-configuration:
        apiVersion: kubeproxy.config.k8s.io/v1alpha1
        clientConnection:
          kubeconfig: /var/vcap/jobs/kube-proxy/config/kubeconfig
        clusterCIDR: 10.200.0.0/16
        iptables:
          masqueradeAll: false
          masqueradeBit: 14
          minSyncPeriod: 0s
          syncPeriod: 30s
        kind: KubeProxyConfiguration
        mode: iptables
        portRange: ""
      tls:
        kubernetes:
          ca: ((tls-kubernetes))
          certificate: ((tls-kubernetes-certificate))
          private_key: ((tls-kubernetes-private_key))
    release: kubo
  name: worker
  networks:
  - name: default
  stemcell: default
  vm_type: small-highmem
name: cfcr
releases:
- name: kubo
  sha1: f9ae87d2def4bf70c2c684711391b405021726c1
  url: https://github.com/cloudfoundry-incubator/kubo-release/releases/download/v0.23.0/kubo-release-0.23.0.tgz
  version: 0.23.0
- name: cfcr-etcd
  sha1: 728839a7ddd44757e31ef0fdbcd131c2be23ab0e
  url: https://github.com/cloudfoundry-incubator/cfcr-etcd-release/releases/download/v1.5.0/cfcr-etcd-release-1.5.0.tgz
  version: 1.5.0
- name: docker
  sha1: f192296243e68150ae66656fc9134a2b2a023184
  url: https://github.com/cloudfoundry-incubator/docker-boshrelease/releases/download/v32.0.0/docker-32.0.0.tgz
  version: 32.0.0
- name: bosh-dns
  sha1: d1aadbda5d60c44dec4a429cda872cf64f6d8d0b
  url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=1.10.0
  version: 1.10.0
- name: bpm
  sha1: 4b6ebfdaa467c04855528172b099e565d679e0f5
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.13.0
  version: 0.13.0
stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest
update:
  canaries: 1
  canary_watch_time: 10000-300000
  max_in_flight: 1
  update_watch_time: 10000-300000
